l_win: 20
l_win_max: 31
batch_size: 16
num_workers: 4
d_model: 16
n_head: 4
dff: 256
num_layers: 4
lr: 0.0001
n_epochs: 40
checkpoint_dir: /home/longmeow/Documents/RUL_Transformer/Checkpoint/
result_file: /home/longmeow/Documents/RUL_Transformer/Result/result.yml