l_win: 100
l_win_max: 31
batch_size: 64
num_workers: 4
d_model: 16
n_head: 2
dff: 64
num_layers: 2
lr: 0.0003
weight_decay: 0.0001
n_epochs: 10
dropout: 0.2
checkpoint_dir: /home/longmeow/Documents/RUL_Transformer/Checkpoint/
result_dir: /home/longmeow/Documents/RUL_Transformer/Result/
